const users = [
'Abel',
'Adeline',
'Al',
'Alexandra',
'Alisha',
'Amanda',
'Anita',
'Aurelio',
'Aurora',
'Beatrice',
'Beau',
'Bethany',
'Brain',
'Brandy',
'Brandy',
'Brenda',
'Brent',
'Carey',
'Cathy',
'Chris',
'Christi',
'Chuck',
'Cliff',
'Clinton',
'Dale',
'Dan',
'Darin',
'Deanne',
'Dewey',
'Dirk',
'Donny',
'Doris',
'Dwayne',
'Earline',
'Elliott',
'Emerson',
'Enrique',
'Erna',
'Evan',
'Flora',
'Foster',
'Grady',
'Gwendolyn',
'Hank',
'Jane',
'Jeremy',
'Jess',
'Jimmie',
'Joanna',
'Joey',
'June',
'Karla',
'Karla',
'Kathy',
'Katy',
'Kim',
'Lindsay',
'Lorraine',
'Lucien',
'Lucy',
'Luke',
'Luz',
'Major',
'Marcy',
'Maria',
'Marina',
'Mauro',
'Meagan',
'Mickey',
'Myron',
'Neva',
'Nolan',
'Ola',
'Omar',
'Pasquale',
'Pearl',
'Peter',
'Phoebe',
'Quinton',
'Raphael',
'Raymond',
'Rebecca',
'Reynaldo',
'Romeo',
'Rosalie',
'Rosanne',
'Scot',
'Shelia',
'Shelly',
'Staci',
'Sue',
'Sybil',
'Sybil',
'Taylor',
'Timothy',
'Tod',
'Vern',
'Victoria',
'Virginia',
'Winfred',
];

const emails = [
    'jonas@verizon.net',
'gumpish@live.com',
'retoh@icloud.com',
'multiplx@me.com',
'rfisher@hotmail.com',
'smeier@verizon.net',
'draper@icloud.com',
'killmenow@att.net',
'irving@gmail.com',
'tbmaddux@optonline.net',
'bdthomas@mac.com',
'ajohnson@live.com',
'jramio@optonline.net',
'baveja@msn.com',
'william@aol.com',
'ralamosm@optonline.net',
'dvdotnet@hotmail.com',
'kaiser@msn.com',
'ivoibs@sbcglobal.net',
'bcevc@icloud.com',
'calin@yahoo.com',
'codex@optonline.net',
'dbanarse@icloud.com',
'osaru@aol.com',
'conteb@comcast.net',
'telbij@yahoo.ca',
'makarow@yahoo.com',
'tubajon@yahoo.com',
'shrapnull@hotmail.com',
'madanm@aol.com',
'ccohen@hotmail.com',
'bmidd@icloud.com',
'magusnet@att.net',
'ghaviv@icloud.com',
'metzzo@live.com',
'marcs@yahoo.com',
'jfriedl@yahoo.ca',
'baveja@hotmail.com',
'mglee@yahoo.ca',
'parsimony@yahoo.com',
'bartak@icloud.com',
'magusnet@gmail.com',
'reeds@hotmail.com',
'thurston@sbcglobal.net',
'mglee@me.com',
'neuffer@mac.com',
'jamuir@mac.com',
'maradine@msn.com',
'jshirley@icloud.com',
'wortmanj@comcast.net',
'amaranth@mac.com',
'scottzed@gmail.com',
'csilvers@live.com',
'jbarta@yahoo.com',
'lipeng@outlook.com',
'seanq@outlook.com',
'balchen@sbcglobal.net',
'onestab@gmail.com',
'sumdumass@sbcglobal.net',
'hedwig@live.com',
'rfisher@hotmail.com',
'ramollin@msn.com',
'hachi@msn.com',
'hllam@yahoo.ca',
'chance@mac.com',
'dialworld@yahoo.com',
'neuffer@icloud.com',
'wetter@sbcglobal.net',
'adillon@icloud.com',
'boein@icloud.com',
'mwandel@sbcglobal.net',
'juliano@icloud.com',
'gator@verizon.net',
'balchen@mac.com',
'rnewman@aol.com',
'eimear@me.com',
'hachi@outlook.com',
'sravani@icloud.com',
'lbecchi@verizon.net',
'webteam@icloud.com',
'mbswan@msn.com',
'zeitlin@yahoo.com',
'carmena@yahoo.ca',
'drhyde@optonline.net',
'delpino@aol.com',
'danneng@comcast.net',
'msroth@yahoo.ca',
'konit@aol.com',
'scarlet@icloud.com',
'hahiss@me.com',
'hakim@comcast.net',
'parksh@yahoo.com',
'kalpol@verizon.net',
'wainwrig@yahoo.ca',
'denton@aol.com',
'mbrown@att.net',
'conteb@sbcglobal.net',
'lcheng@yahoo.com',
'violinhi@me.com',
'hstiles@gmail.com',

]

const thoughts = [
    'The scream in your head will never be out of breath.',
'Do fish in water have their hidden life where they go to school, hang out, study, and get married?',
'If everyone had roller skates instead of feet, would there be cars or would they go rollerblading everywhere?',
'We will never know what memories we had as children and we will never remember them.',
'We know our parents for whole our life, while they know us only part of their lives.',
'Someone was born at this very moment, and someone lost his life at this very moment.',
'Our brain has never experienced some things, and yet it can tailor a scenario in its head as if it had happened.',
'If the tomato is a fruit, then ketchup is the jam.',
'If I were a book, what title would I have?',
' Valentine’s Day is known for its red color, red roses, red hearts … Would it be strange if another color was used for Valentine’s Day instead of red? And why red? Why does red associate us with love?',
' The hospital where you were born is the only building you left without entering.',
' Humans invented the sounds produced by dinosaurs.',
' Maybe it’s better not to kill the spider, because if I kill him, his family and friends can come to the funeral and in that way, I will summon many more spiders.',
' Who invented the words and names of certain objects and how did it occur to someone to call a chair just like that – “chair”?',
' How does our voice in our head sound?',
' It is very important to have someone who lets you be what you are and nourishes your mind and your soul, not your ego.',
' What would happen to us without love? We would not be beings who feel and live for love, we would be just a mere and quiet existence.',
' It is better to be alone and happy in the four walls of your head than to suffer someone’s disrespect, just because you are afraid of loneliness.',
' Love just happens and doesn’t ask you a question, but gives you an answer.',
' Is there a destiny or is it all just a coincidence?',
' How is it possible for our heart to love so many times, break so many times for someone, and be whole again and ready to regenerate and give new love?',
];

// Get a random item
const randomItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

// Random full name
const randomName = () => {
   return `${randomItem(users)} ${randomItem(users)}`;
}

const randomEmail = (username) => {
    const name = username.split(" ")
    const temp = randomItem(emails);
    return emailAdd = (name[0] + temp);
};


const randomThoughts = () => {
    return randomItem(thoughts);
};

module.exports = { randomName, randomThoughts, randomEmail };